### ISSUE TITLE
Unity .meta files missing in repo

### ISSUE THREAD

**Issue by Xriuk** [microsoft/MixedReality-QRCode-Sample#4]
The Unitys .meta files are missing for this repository, this invalidates the created prefabs as Unity loses track of the referenced scripts.
Unity .meta files should be stored in version control.

**Comment by PablOnk** [comment]
Package folder doesn´t exists. Please help. And where i have to put the VCRTFFowarders folder?

**Comment by ABinettiCap** [comment]
Same issues ... QRCodeManager prefab and Axis prefab are missing.

**Comment by cheles** [comment]
@ABinettiCap  they do exists  under Prefabs folder. there seems to be a mismatch between guids. we will check this further. In Unity, you can just drag&drop those 2 from Prefabs folder to Hierarchy column

**Comment by KiriUbu** [comment]
i have a simular Problem. All the references to the scripts are also gone. Could may be some just tell me with scripts should be connected to witch Prefab? 

![Screenshot 2022-05-21 150235](https://user-images.githubusercontent.com/47858105/169652778-89f633db-2b1b-4cae-b0a5-949b60b5a583.png)

**Comment by cheles** [comment]
you are right @Xriuk  @KiriUbu. we are working on fixing this. meanwhile, QRCodesManager should look like this: 
![image](https://user-images.githubusercontent.com/1419060/171642359-834bf215-bc2c-4a84-825b-93481f098c6a.png)

**Comment by FireDragonGameStudio** [comment]
Same problem here, where all prefabs and script references are broken. :/

**Comment by cheles** [comment]
@FireDragonGameStudio  we are working on this. meanwhile, you can remove those 2 prefabs  and re-add them to the project. QRCodesManager scripts should look like above screenshot.

**Comment by petergu684** [comment]
This could be easily solved by deleting the `.gitignore` file in the root, which doesn't seem to do anything other than adding `.meta` into ignore list.

**Comment by SashelI** [comment]
> you are right @Xriuk @KiriUbu. we are working on fixing this. meanwhile, QRCodesManager should look like this: ![image](https://user-images.githubusercontent.com/1419060/171642359-834bf215-bc2c-4a84-825b-93481f098c6a.png)

Hi, Could you provide the scripts that must be on the "QRCode" prefab aswell ? thanks

**Comment by cheles** [comment]
![image](https://user-images.githubusercontent.com/1419060/185662667-76d47993-4e07-464d-8892-37c189638308.png)
meanwhile, you can use https://github.com/chgatla-microsoft/QRTracking sample built with MRTK 2.5 and Unity 2020 / Built-in XR or  https://github.com/yl-msft/QRTracking on OpenXR / Unity 2020

**Comment by SashelI** [comment]
Thanks !

**Comment by Heavenswind** [comment]
has this been updated to Unity 2021? what is the latest versions of Unity + XR and MRTK we can use ?

**Comment by chgatla-microsoft** [comment]
project updated.
