### ISSUE TITLE
Packages folder doesnt exists!

### ISSUE THREAD

**Issue by PablOnk** [microsoft/MixedReality-QRCode-Sample#5]
Please add the Packages folders

**Comment by cheles** [comment]
@PablOnk please follow the instructions on readme 
Prerequisites
Install the [latest Mixed Reality tools](https://docs.microsoft.com/windows/mixed-reality/develop/install-the-tools?tabs=unity)
Install the [recommended Unity version](https://docs.microsoft.com/windows/mixed-reality/develop/install-the-tools?tabs=unity#install-your-engine-of-choice)
Download the [QR code NuGet package](https://www.nuget.org/Packages/Microsoft.MixedReality.QR)

Once you do this, run MRT Feature tool, add MRTF + Standard assets to project. Check that WMR is enabled under XR Plug-in Management. 

Unity will restore project's packages so there is no need to have packages folder on repo.

**Comment by cxiliu** [comment]
> Once you do this, run MRT Feature tool, add MRTF + Standard assets to project. Check that WMR is enabled under XR Plug-in Management.

I guess this is obvious given the provided packages, but it would prevent confusion if it's included in the setup steps.

**Comment by chgatla-microsoft** [comment]
Project updated.
