### ISSUE TITLE
Cannot Build or Run due to missing references

### ISSUE THREAD

**Issue by NicoSchirmeier** [microsoft/MixedReality-QRCode-Sample#8]
**Which sample are you reporting a bug in?**

MixedReality-QRCodeSample

**Describe the bug**
When trying to run/build the sample i get the following errors: 
![image](https://user-images.githubusercontent.com/56126372/181033295-210524e9-b98c-4c2b-a4e7-66a7b1cc1849.png)

**To Reproduce**
1. Install Unity (Same Version as sample)
2. Open Sample downloaded of github
3. Switch Platform to Universal Windows Platform with settings for HoloLens devices 
4. Fix missing nuget packages (QR Code package as described in readme) and install fundation and openXR with ms mixed reality feature tool

**Expected behavior**
After installing the fundation and qr code packages no errors should remain in the project

**Configuration**

* Language/architecture/flavor: c#, unity
* Windows version: 22000.795

**Comment by NicoSchirmeier** [comment]
i could now build the sample using older versions of the foundation package (2.7.0) seems to work for me. I still need to figure some things out but at least this kinda works now. Is there any documentation on which versions (Unity, Foundation, OpenXR, etc.) are tested to work with each other?

**Comment by chgatla-microsoft** [comment]
Project updated.

**Comment by Morgan-6Freedom** [comment]
Does it mean it work with when checkign OpenXR instead of Windows Mixed Reality in the XR Plug-in Management ?


Because for me, when building with OpenXR checked, I have an issue with UnityEngine.XR.WindowsMR Line 75 in SpatialGraphCoordinateSystem

**Comment by GPROWIRELESS** [comment]
> Does it mean it work with when checkign OpenXR instead of Windows Mixed Reality in the XR Plug-in Management ?
> 
> Because for me, when building with OpenXR checked, I have an issue with UnityEngine.XR.WindowsMR Line 75 in SpatialGraphCoordinateSystem

I have the same issue, using unity 2021.3.4f1, visual studio 2022, building a project with eye tracker and QRCode.
