### ISSUE TITLE
Possible to get pose of QR code with Holographic Remoting?

### ISSUE THREAD

**Issue by felixvh** [microsoft/MixedReality-QRCode-Sample#9]
Hey everyone,

this is a question, not a bug report. I was wondering if it is possible to obtain the pose of the QR code with Holographic Remoting? Unfortunately, I don't have a HoloLens currently - otherwise I would try myself. 

Thanks!

**Comment by felixvh** [comment]
In case somebody has the same question: I could not make it work this sample but found another example in which they used OpenXR instead of the Windows XR Plugin. In this case it work.

https://github.com/yl-msft/QRTracking

**Comment by vimusc** [comment]
Hi @felixvh,

in general, it is possible to use QR codes with Holographic Remoting.
You can find the remoting QR sample [here](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/blob/main/remote/common/holographic/QRCodeRenderer.cpp).

This Unity sample seems to be not quite up to date. After following your steps and addressing various Unity errors/warnings, I got it in a state, where the CreateCoordinateSystemForNode() call succeeded.
Nevertheless, I would recommend using the never OpenXR API and the sample you linked [before](https://github.com/microsoft/MixedReality-QRCode-Sample/issues/9#issuecomment-1228419314).

Do you need further help?

Best regards
Vincent

**Comment by felixvh** [comment]
Hi @vimusc,

thanks for your reply! I continued my work with the OpenXR API so I don't need further help, thanks! I wasn't sure if I should leave the issue open as the actual problem wasn't solved. But I will close it now.

Thanks again and best regards
Felix
